name: Deploy FastAPI App

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch (includes PR merge)

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Adjust the timeout to 30 minutes for deployment

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (for cross-platform support if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t jessiecloudops/fastapi-app:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push jessiecloudops/fastapi-app:latest

      # SSH to GCP VM and deploy
      - name: SSH to GCP VM and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          script: |
            # Pull the latest Docker image from Docker Hub
            sudo docker pull jessiecloudops/fastapi-app:latest
            
            # Stop and remove any previous containers
            sudo docker stop fastapi-container || true
            sudo docker rm fastapi-container || true

            # Run the new container
            sudo docker run -d --name fastapi-container -p 8000:8000 jessiecloudops/fastapi-app:latest
            
            # Restart nginx service to apply any new configurations
            sudo systemctl restart nginx || true

      # Ensure that the system is not stuck
      - name: Check if the container is running
        run: |
          docker ps | grep fastapi-container
